import type { ReviewComment, Severity } from '../review/types.js'
import type { ReviewStore } from '../store/types.js'

const DAY_MS = 24 * 60 * 60 * 1000

const REPOS = [
  { owner: 'acme', repo: 'widgets' },
  { owner: 'acme', repo: 'billing-api' },
  { owner: 'kartik', repo: 'url-shortener' },
]
const AUTHORS = ['kartik', 'sam', 'priya']
const TITLES = [
  'Add host support',
  'Fix race in cache refill',
  'Bump dependencies',
  'Refactor auth middleware',
  'Add retry to webhook sender',
  'Handle empty payload',
]
const FILES = ['src/app.ts', 'src/cache.ts', 'lib/auth.ts']
const SEVERITIES: Severity[] = ['critical', 'warning', 'suggestion']
const BODIES = [
  'This query is built from user input without escaping; use a parameterised query.',
  'The promise is not awaited, so errors are swallowed and the response is sent early.',
  'Consider extracting this into a helper; the same logic appears in two places above.',
  'Missing null check: `user` can be undefined when the session has expired.',
]

/** Reviews started per day, oldest first (14 days). Quiet days make the chart readable. */
const PER_DAY = [0, 2, 3, 1, 0, 4, 6, 2, 3, 0, 5, 7, 3, 4]

/**
 * Fills a store with believable fake reviews spread over the last two weeks, so the dashboard
 * can be explored without a GitHub App, an API key or a database. Fully deterministic.
 */
export async function seedDemoStore(store: ReviewStore, now: Date = new Date()): Promise<number> {
  let n = 0
  for (let i = 0; i < PER_DAY.length; i++) {
    const daysAgo = PER_DAY.length - 1 - i
    for (let k = 0; k < PER_DAY[i]!; k++) {
      n++
      const { owner, repo } = REPOS[n % REPOS.length]!
      const startedAt = new Date(now.getTime() - daysAgo * DAY_MS - k * 3_600_000)
      const status = n % 9 === 0 ? 'failed' : n % 5 === 0 ? 'skipped' : 'completed'

      const record = await store.claim(
        { owner, repo, prNumber: n, headSha: `demo${String(n).padStart(4, '0')}abcdef` },
        {
          prTitle: TITLES[n % TITLES.length]!,
          prUrl: `https://github.com/${owner}/${repo}/pull/${n}`,
          author: AUTHORS[n % AUTHORS.length]!,
        },
      )
      if (!record) continue

      const comments: ReviewComment[] =
        status === 'completed'
          ? Array.from({ length: n % 4 }, (_, c) => ({
              path: FILES[c % FILES.length]!,
              line: 10 + c * 7,
              severity: SEVERITIES[(n + c) % SEVERITIES.length]!,
              body: BODIES[(n + c) % BODIES.length]!,
              fingerprint: `demo-${n}-${c}`,
            }))
          : []
      const filesReviewed = status === 'completed' ? 2 + (n % 5) : 0

      await store.update(record.id, {
        status,
        startedAt,
        finishedAt: new Date(startedAt.getTime() + 3000 + n * 700),
        durationMs: 3000 + n * 700,
        filesReviewed,
        filesSkipped: 1,
        chunks: 1 + (n % 2),
        droppedChunks: 0,
        model: 'claude-sonnet-5-5',
        inputTokens: 4000 + n * 350,
        outputTokens: 300 + n * 40,
        comments,
        skipReason: status === 'skipped' ? 'draft pull request' : undefined,
        error: status === 'failed' ? 'every model call failed' : undefined,
        summary:
          status === 'completed'
            ? `### 🤖 Automated review\nReviewed ${filesReviewed} files and left ${comments.length} comments.\n\n_Generated by an AI model and may be wrong._`
            : undefined,
      })
    }
  }
  return n
}
