import { vi } from 'vitest'
import type { ReviewDetail, ReviewPage, ReviewSummary, Stats } from '../api'

export const TOKEN = 'good-token-1234567890'

export const stats: Stats = {
  totals: {
    reviews: 12,
    completed: 9,
    skipped: 2,
    failed: 1,
    commentsPosted: 21,
    filesReviewed: 40,
    inputTokens: 52_000,
    outputTokens: 4_500,
    avgDurationMs: 8_400,
  },
  bySeverity: { critical: 3, warning: 8, suggestion: 10 },
  byDay: [
    { date: '2026-03-08', reviews: 0, comments: 0 },
    { date: '2026-03-09', reviews: 3, comments: 4 },
    { date: '2026-03-10', reviews: 9, comments: 17 },
  ],
  byRepo: [
    { repo: 'acme/widgets', reviews: 8, comments: 15 },
    { repo: 'acme/billing', reviews: 4, comments: 6 },
  ],
}

export const emptyStats: Stats = {
  ...stats,
  totals: { ...stats.totals, reviews: 0, completed: 0, skipped: 0, failed: 0, commentsPosted: 0 },
  byDay: [],
  byRepo: [],
}

export function summary(over: Partial<ReviewSummary> = {}): ReviewSummary {
  return {
    id: 'r1',
    owner: 'acme',
    repo: 'widgets',
    prNumber: 7,
    headSha: 'abcdef1234567',
    prTitle: 'Add host support',
    prUrl: 'https://github.com/acme/widgets/pull/7',
    author: 'kartik',
    status: 'completed',
    filesReviewed: 3,
    filesSkipped: 1,
    chunks: 1,
    droppedChunks: 0,
    model: 'claude-sonnet-5-5',
    inputTokens: 4000,
    outputTokens: 300,
    startedAt: new Date(Date.now() - 5 * 60_000).toISOString(),
    durationMs: 12_000,
    commentCount: 2,
    ...over,
  }
}

export function page(items: ReviewSummary[], over: Partial<ReviewPage> = {}): ReviewPage {
  return { total: items.length, page: 1, limit: 15, items, ...over }
}

export const detail: ReviewDetail = (() => {
  const { commentCount: _unused, ...rest } = summary()
  return {
    ...rest,
    summary: '### 🤖 Automated review\nReviewed 3 files and left 2 comments.\n\n_Generated by an AI model._',
    comments: [
      { path: 'src/app.ts', line: 12, severity: 'critical', body: 'HOST may be undefined.' },
      { path: 'src/app.ts', line: 14, severity: 'suggestion', body: 'Always returns true.' },
      { path: 'src/cache.ts', line: 3, severity: 'warning', body: 'Promise is not awaited.' },
    ],
  }
})()

type Handler = (url: URL, init?: RequestInit) => { status?: number; body?: unknown }

/**
 * Replaces fetch with a fake API. `handler` receives every request and returns the reply;
 * requests are also recorded so tests can check the query string and auth header.
 */
export function mockApi(handler: Handler) {
  const calls: { path: string; search: string; auth: string | null }[] = []
  const fake = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = new URL(String(input), 'http://localhost')
    const headers = new Headers(init?.headers)
    calls.push({ path: url.pathname, search: url.search, auth: headers.get('authorization') })
    const { status = 200, body } = handler(url, init)
    return new Response(JSON.stringify(body ?? {}), { status, headers: { 'content-type': 'application/json' } })
  })
  vi.stubGlobal('fetch', fake)
  return { calls, fake }
}

/** A fake backend that accepts only TOKEN and serves the given data. */
export function authedApi(data: { stats?: Stats; reviews?: (url: URL) => ReviewPage; review?: ReviewDetail } = {}) {
  return mockApi((url, init) => {
    const auth = new Headers(init?.headers).get('authorization')
    if (auth !== `Bearer ${TOKEN}`) return { status: 401, body: { error: 'Unauthorized' } }
    if (url.pathname === '/api/stats') return { body: data.stats ?? stats }
    if (url.pathname === '/api/reviews') return { body: (data.reviews ?? (() => page([summary()])))(url) }
    if (url.pathname.startsWith('/api/reviews/')) {
      return data.review ? { body: data.review } : { status: 404, body: { error: 'Not found' } }
    }
    return { status: 404 }
  })
}
